#!/usr/bin/env python3
"""Pull accepted edits from the online editor (Supabase) and apply the ones
that map cleanly onto a Built-for-Wonder.docx paragraph. Run this once the
editor is done editing.

Every editable block in the online editor (editor.js EDIT_SELECTOR: p, h1-h4,
li, blockquote, figcaption) gets tracked, but not every block's text lives in
the DOCX verbatim -- headers, hook lines, key reads, pattern-interrupt boxes,
and figure captions are generated by build-book.py, not extracted from the
manuscript. So each edit is classified by whether its ORIGINAL text matches
exactly one paragraph in the DOCX:

  - exactly 1 match  -> AUTO-APPLIED to the DOCX (run-aware, preserves
                        formatting when the whole paragraph shares one style;
                        backed up first)
  - 0 matches        -> DESIGN CONTENT, left alone. Likely lives in a
                        build-book.py config dict (HOOK_LINES, KEY_READS,
                        PATTERN_INTERRUPTS, WHAT_YOU_JUST_DID, a figure
                        caption, ...) and needs a human to find + apply it.
  - >1 matches        -> AMBIGUOUS, left alone (could patch the wrong one).

Notes (comments left by the editor) are never auto-applied -- they're just
included in the report for a human to read and act on.

Default is a dry run (classify + report, no writes). Pass --apply to
actually patch the DOCX and refresh manuscript-extracted.txt.

Usage:
  python3 apply-editor-edits.py              # dry run, writes a report
  python3 apply-editor-edits.py --apply       # patch the DOCX for real
"""
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import requests
from docx import Document

ROOT = Path(__file__).parent
DOCX = ROOT / "Built-for-Wonder.docx"
MANUSCRIPT = ROOT / "manuscript-extracted.txt"
CONFIG_JS = ROOT / "editor-config.js"
BACKUPS = ROOT / "backups"
REPORT = ROOT / "editor-merge-report.md"
EXTRACT_SCRIPT = ROOT / "extract_manuscript.py"


def norm(s):
    return re.sub(r"\s+", " ", (s or "")).strip()


def load_supabase_config():
    text = CONFIG_JS.read_text(encoding="utf-8")
    url = re.search(r'supabaseUrl:\s*"([^"]+)"', text)
    key = re.search(r'supabaseAnonKey:\s*"([^"]+)"', text)
    if not url or not key or not url.group(1) or not key.group(1):
        sys.exit("editor-config.js has no Supabase URL/key configured -- nothing to fetch.")
    return url.group(1).rstrip("/"), key.group(1)


def fetch(base, key, table, order=None):
    url = f"{base}/rest/v1/{table}?select=*"
    if order:
        url += f"&order={order}"
    r = requests.get(url, headers={"apikey": key, "Authorization": f"Bearer {key}"})
    r.raise_for_status()
    return r.json()


def all_paragraphs(doc):
    """Body paragraphs + paragraphs inside every table cell."""
    ps = list(doc.paragraphs)
    for t in doc.tables:
        for row in t.rows:
            for cell in row.cells:
                ps.extend(cell.paragraphs)
    return ps


def run_fmt(r):
    return (bool(r.bold), bool(r.italic), bool(r.underline))


def paragraph_text(p):
    return "".join(r.text or "" for r in p.runs)


def try_apply(p, old, new, commit=True):
    """Substring-and-run-aware replace (same algorithm this repo already
    uses in apply_audit_fixes_20260705.py). A DOCX <w:p> paragraph can hold
    several build-book.py-visible "paragraphs" glued together by manual line
    breaks, so an edit's ORIGINAL text is usually a substring of the DOCX
    paragraph, not the whole thing -- matching only whole-paragraph equality
    would silently miss most real edits. Returns ('applied'|'skip-...', detail).
    With commit=False, computes the same status/detail but never writes to
    the runs -- used for the dry-run report so nothing mutates in memory."""
    runs = p.runs
    if not runs:
        return ("skip-no-runs", "no runs")
    joined = "".join(r.text or "" for r in runs)
    idx = joined.find(old)
    if idx < 0:
        return ("skip-not-found", "string not in paragraph")
    if joined.find(old, idx + 1) >= 0:
        return ("skip-multi-in-paragraph", "string appears >1x in this paragraph")
    end = idx + len(old)
    pos = 0
    start_run = end_run = None
    local_start = local_end = None
    for ri, r in enumerate(runs):
        rt = r.text or ""
        rstart, rend = pos, pos + len(rt)
        if start_run is None and rstart <= idx < rend:
            start_run, local_start = ri, idx - rstart
        if rstart < end <= rend:
            end_run, local_end = ri, end - rstart
        pos = rend
    if start_run is None or end_run is None:
        return ("skip-run-span", "could not map run span")
    if start_run == end_run:
        if commit:
            r = runs[start_run]
            r.text = r.text[:local_start] + new + r.text[local_end:]
        return ("applied", "single-run")
    fmts = {run_fmt(runs[ri]) for ri in range(start_run, end_run + 1)}
    if len(fmts) > 1:
        return ("skip-mixed-fmt", f"spans runs {start_run}-{end_run} with mixed formatting")
    if commit:
        prefix = (runs[start_run].text or "")[:local_start]
        suffix = (runs[end_run].text or "")[local_end:]
        runs[start_run].text = prefix + new + suffix
        for ri in range(start_run + 1, end_run + 1):
            runs[ri].text = ""
    return ("applied", f"collapsed runs {start_run}-{end_run} (uniform fmt)")


def extract_manuscript():
    """Refresh manuscript-extracted.txt from the patched DOCX using this
    repo's real extraction script (extract_manuscript.py) -- NOT a
    reimplementation. That script does heading-style-driven chapter/part
    structuring (CHAPTER N markers, PART dividers, TOC skipping, corrupted-
    heading fixups); a naive raw-paragraph dump is a different format and
    will break build-book.py's parser."""
    subprocess.run([sys.executable, str(EXTRACT_SCRIPT)], cwd=str(ROOT), check=True)
    # The tracked file is CRLF (last generated on Windows); Python's text-mode
    # write on macOS emits bare LF. Normalize back to CRLF so git only shows
    # the paragraphs that actually changed, not a whole-file line-ending diff.
    raw = MANUSCRIPT.read_bytes().replace(b"\r\n", b"\n")
    MANUSCRIPT.write_bytes(raw.replace(b"\n", b"\r\n"))


def main():
    apply_changes = "--apply" in sys.argv

    base, key = load_supabase_config()
    print(f"Fetching from {base} ...")
    edits = fetch(base, key, "edits", order="chapter.asc")
    notes = fetch(base, key, "notes", order="created_at.asc")
    print(f"  {len(edits)} edit(s), {len(notes)} note(s)")

    if not edits and not notes:
        print("Nothing to do -- editor tables are empty.")
        return 0

    doc = None
    paras = []
    if edits:
        doc = Document(str(DOCX))
        paras = all_paragraphs(doc)

    manuscript_lines = set()
    if MANUSCRIPT.exists():
        manuscript_lines = {norm(l) for l in MANUSCRIPT.read_text(encoding="utf-8").split("\n")}

    applied, design_content, ambiguous = [], [], []

    for e in edits:
        # match on the DOCX's own text, not norm() -- try_apply needs the
        # exact substring (with original whitespace/newlines) to locate runs
        old_raw = e.get("original") or ""
        old = old_raw.strip()
        new = e.get("edited") or ""
        if not old or not new or norm(old) == norm(new):
            continue
        cands = [p for p in paras if old in paragraph_text(p)]
        if len(cands) == 0:
            # fall back to normalized-whitespace search in case the DOCX has
            # different internal line breaks than what the browser rendered
            cands = [p for p in paras if norm(old) in norm(paragraph_text(p))]
        if len(cands) == 0:
            design_content.append(e)
        elif len(cands) > 1:
            ambiguous.append(e)
        else:
            status, detail = try_apply(cands[0], old, new, commit=apply_changes)
            if status == "applied":
                applied.append((e, detail))
            elif norm(old) in manuscript_lines:
                ambiguous.append(e)  # real manuscript text, but not safely locatable/patchable
            else:
                design_content.append(e)

    if apply_changes and applied:
        BACKUPS.mkdir(exist_ok=True)
        ts = datetime.now().strftime("%Y%m%d-%H%M%S")
        shutil.copy2(DOCX, BACKUPS / f"Built-for-Wonder-pre-editor-merge-{ts}.docx")
        shutil.copy2(DOCX, BACKUPS / "Built-for-Wonder-pre-editor-merge.docx")
        doc.save(str(DOCX))
        extract_manuscript()
        print(f"Patched DOCX -> {DOCX.name} (backup in backups/), refreshed {MANUSCRIPT.name}")

    # ---- report ----
    lines = [f"# Editor merge report — {datetime.now().strftime('%Y-%m-%d %H:%M')}", ""]
    lines.append("DRY RUN (no files changed) -- re-run with --apply to patch the DOCX." if not apply_changes
                  else "APPLIED -- Built-for-Wonder.docx patched, manuscript-extracted.txt refreshed.")
    lines.append("")
    lines.append(f"## Auto-{'applied' if apply_changes else 'applicable'} — matched a single DOCX paragraph ({len(applied)})")
    lines.append("")
    for e, detail in applied:
        lines.append(f"- **[{e.get('chapter_title') or e.get('chapter')}]** ({e.get('author')}, {detail})")
        lines.append(f"  - was: {e['original'][:120]!r}")
        lines.append(f"  - now: {e['edited'][:120]!r}")
    if not applied:
        lines.append("_(none)_")
    lines.append("")

    lines.append(f"## Needs manual handling — no DOCX match, likely generated design content ({len(design_content)})")
    lines.append("_Check build-book.py's HOOK_LINES / KEY_READS / PATTERN_INTERRUPTS / WHAT_YOU_JUST_DID dicts, or a figure caption._")
    lines.append("")
    for e in design_content:
        lines.append(f"- **[{e.get('chapter_title') or e.get('chapter')}]** ({e.get('author')})")
        lines.append(f"  - was: {e['original'][:160]!r}")
        lines.append(f"  - now: {e['edited'][:160]!r}")
    if not design_content:
        lines.append("_(none)_")
    lines.append("")

    lines.append(f"## Ambiguous — matched more than one DOCX paragraph, skipped ({len(ambiguous)})")
    lines.append("")
    for e in ambiguous:
        lines.append(f"- **[{e.get('chapter_title') or e.get('chapter')}]** ({e.get('author')})")
        lines.append(f"  - was: {e['original'][:160]!r}")
        lines.append(f"  - now: {e['edited'][:160]!r}")
    if not ambiguous:
        lines.append("_(none)_")
    lines.append("")

    lines.append(f"## Notes from the editor ({len(notes)})")
    lines.append("_Not auto-applied -- read and act on manually._")
    lines.append("")
    for n in notes:
        lines.append(f"- **[{n.get('chapter_title') or n.get('chapter')}]** {n.get('author')} — \"{n.get('quote')}\"")
        lines.append(f"  - {n.get('body')}")
    if not notes:
        lines.append("_(none)_")
    lines.append("")

    if apply_changes and applied:
        lines.append("## Next step")
        lines.append("Review the design-content + ambiguous items above, hand-apply what's needed, "
                      "then rebuild: `python3 build_all.py` (or `build-book.py` + `build-gated.py`), "
                      "copy the gated build to the deploy target, commit, push.")

    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nApplied: {len(applied)}  Design-content: {len(design_content)}  Ambiguous: {len(ambiguous)}  Notes: {len(notes)}")
    print(f"Report -> {REPORT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
